# Generated by Django 2.0.6 on 2018-10-03 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20181001_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='image.Image'),
        ),
    ]
