# Generated by Django 2.0.8 on 2018-10-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20181009_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='ingredients',
            new_name='recipes',
        ),
    ]
